[Service]
SyslogIdentifier=collectd
RuntimeDirectory=collectd
ExecStartPre=/bin/bash /usr/share/adsb-graphs/readback.sh
ExecStartPre=/usr/sbin/collectd -t
ExecStopPost=/bin/bash /usr/share/adsb-graphs/writeback.sh
Restart=always
RestartSec=10
