#lighttpd configuration for adsb-graphs

alias.url += (
  "/adsb-graphs/graphs/" => "/run/adsb-graphs/",
  "/adsb-graphs/" => "/usr/share/adsb-graphs/html/",
)

# redirect the slash-less URL
url.redirect += (
  "^/adsb-graphs/graphs.html$" => "/adsb-graphs/",
  "^/adsb-graphs$" => "/adsb-graphs/",
  "^/graph1090$" => "/adsb-graphs/",
  "^/graph1090/$" => "/adsb-graphs/",
  "^/perf$" => "/adsb-graphs/",
  "^/perf/$" => "/adsb-graphs/",
)

# Add CORS header
$HTTP["url"] =~ "^/adsb-graphs/.*" {
  setenv.add-response-header += (
          "Access-Control-Allow-Origin" => "*",
          "Cache-Control" => "public, max-age=0",
          )
}
