# serve adsb-graphs directly on port 8542
$SERVER["socket"] == ":8542" {

  alias.url += (
      "/graphs/" => "/run/adsb-graphs/",
      "/" => "/usr/share/adsb-graphs/html/",
      )

    url.redirect += (
        "^$" => "/"
        )

    $HTTP["url"] =~ "^/.*" {
      setenv.add-response-header += (
          "Access-Control-Allow-Origin" => "*",
          "Cache-Control" => "public, max-age=0",
          )
    }
}
